### PR TITLE
Fix Texture bug on fully grown Cocoa Lesbeans

### PR DESCRIPTION
**Pull request by Thinkseal**

### CODE REVIEW

**Comment by blryface** [comment]
I'll have to test if the current one is broken to begin with
##### I can't believe "fixed texter bug" is gonna be in the commit history lol

**Comment by worldwidepixel** [comment]
This is a good texture. I recommend pulling.

**Review by blryface — APPROVED** [review]
lgtm, works in-game

**Comment by blryface** [comment]
> This is a good texture. I recommend pulling.

you mean merging?

**Pull request merged**
